import type { Metadata } from "next";
import "./globals.css";
import SideNavBar from '../ui-components/SideNavBar';
import BottomNavBar from '../ui-components/BottomNavBar';

export const metadata: Metadata = {
  title: "Personal Finance App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`text-(--font-family) bg-(--background-color)`}
    >
      <body className="flex">
        <div className={`hidden md:block`}>
          <SideNavBar />
        </div>
        <main className={`ml-6 md:ml-16`}>{children}</main>
        <div className={`block md:hidden`}>
          <BottomNavBar />
        </div>
      </body>
    </html>
  );
}
