import type { Metadata } from "next";
import "./globals.css";
import SideNavBar from '../ui-components/SideNavBar';
import BottomNavBar from '../ui-components/BottomNavBar';

export const metadata: Metadata = {
  title: "Personal Finance App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const isActivePage:boolean = false;

  return (
    <html
      lang="en"
      className={`text-(--font-family) h-full antialiased bg-(--background-color)`}
    >
      <body className="min-h-full">
        <div className={`hidden md:block`}>
          <SideNavBar />
        </div>
        <div className={`block md:hidden`}>
          <BottomNavBar isActive={isActivePage}/>
        </div>
        {children}
      </body>
    </html>
  );
}
