import type { Metadata } from "next";
import "./globals.css";
import NavBar from '../ui-components/NavBar';

export const metadata: Metadata = {
  title: "Personal Finance App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`text-(--font-family) h-full antialiased bg-(--background-color)`}
    >
      <body className="min-h-full">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
